apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.coordinator" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
spec:
  selector:
    matchLabels:
      app: {{ template "presto.name" . }}
      release: {{ .Release.Name }}
      component: coordinator
  template:
    metadata:
      labels:
        app: {{ template "presto.name" . }}
        release: {{ .Release.Name }}
        component: coordinator
    spec:
{{ if .Values.containerSpec }}
{{ toYaml .Values.containerSpec | indent 6 }}
{{ end }}
      volumes:
        - name: catalog-volume
          configMap:
            name: {{ template "presto.name" . }}-catalog
        - name: config-volume
          configMap:
            name: {{ template "presto.coordinator" . }}
      containers:
        - name: {{ .Chart.Name }}-coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          command: ["python3", "presto-entrypoint.py"]
          args:
            - "--environment={{ default "production" .Values.presto.environment }}"
            - "--discovery-uri={{ template "presto.fullname" . }}"
            - "--discovery-port={{ default 80 .Values.presto.servicePort }}"
            - "--log-level={{ default "ERROR" .Values.presto.logLevel }}"
            - "--coordinator"
          tty: true
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{ if .Values.environmentVariables }}
{{ toYaml .Values.environmentVariables | indent 12 }}
{{ end }}
          volumeMounts:
            - mountPath: /presto/templates/catalog
              name: catalog-volume
            - mountPath: /presto/templates/custom_conf
              name: config-volume
          resources:
{{ toYaml .Values.coordinatorResources | indent 12 }}
    {{- with .Values.coordinatorNodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.coordinatorAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.coordinatorTolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

---
